name: tato
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0 # Widget para exibir mapas interativos no aplicativo.
  latlong2: ^0.9.0 # Lida com coordenadas geográficas (lat/long) para o mapa.
  flutter_tts: ^3.8.3 # Converte texto em fala para a acessibilidade de áudio.
  shared_preferences: ^2.2.2  # Armazena dados simples no dispositivo (primeiro acesso, etc).
#  speech_to_text: ^6.6.0 # Reconhece a fala do usuário, convertendo voz em texto.
  geocoding: ^2.1.1 # Converte endereços de texto em coordenadas geográficas.

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - images/