// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALlzekszIwhnjuhyFua_RFFcRGcsjsBTk',
    appId: '1:79862490037:web:1f3068214084ed58f66ffc',
    messagingSenderId: '79862490037',
    projectId: 'tato-senai-caxias',
    authDomain: 'tato-senai-caxias.firebaseapp.com',
    storageBucket: 'tato-senai-caxias.firebasestorage.app',
    measurementId: 'G-0J44BR46ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS93C3Q6IK2Y2PJaG6dJ9iqwFDuk6oSHc',
    appId: '1:79862490037:android:d6330e6936a7cb21f66ffc',
    messagingSenderId: '79862490037',
    projectId: 'tato-senai-caxias',
    storageBucket: 'tato-senai-caxias.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALlzekszIwhnjuhyFua_RFFcRGcsjsBTk',
    appId: '1:79862490037:web:60a8020ec859cb01f66ffc',
    messagingSenderId: '79862490037',
    projectId: 'tato-senai-caxias',
    authDomain: 'tato-senai-caxias.firebaseapp.com',
    storageBucket: 'tato-senai-caxias.firebasestorage.app',
    measurementId: 'G-P0R5FQCE30',
  );
}
